package self.mohekkus.gridlayoutapplication;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;

import java.util.List;

public class CustomAdapter extends RecyclerView.Adapter<CustomAdapter.ViewHolder> {

    // Data holder
    private final List<String> adapterList;

    // Constructor data
    public CustomAdapter(List<String> list) {
        adapterList = list;
    }

    // Generated by RecyclerView.Adapter<CustomAdapter.ViewHolder>
    @NonNull
    @Override
    public CustomAdapter.ViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        return new ViewHolder(
                LayoutInflater
                        .from(parent.getContext())
                        .inflate(R.layout.item_gridview, parent,false)
        );
    }

    @Override
    public void onBindViewHolder(@NonNull CustomAdapter.ViewHolder holder, int position) {
        View v = holder.itemView;
        String dataPosition = adapterList.get(position);

        TextView textView =  v.findViewById(R.id.textview_grid);
        textView.setText(dataPosition);
        textView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Toast.makeText(v.getContext(), dataPosition, Toast.LENGTH_SHORT).show();
            }
        });
    }

    @Override
    public int getItemCount() {
        return adapterList.size(); // matching data length
    }

    // Created static class extend RecyclerView.ViewHolder
    public static class ViewHolder extends RecyclerView.ViewHolder {

        // Generated by RecyclerView.ViewHolder
        public ViewHolder(@NonNull View itemView) {
            super(itemView);
        }
    }
}
